In [1]:
import numpy as np
import pandas as pd


In [2]:
df = pd.read_csv(r"C:\Users\Asad Raja\Downloads\bangalore house price prediction OHE-data.csv")

In [3]:
df.head()

bath  balcony  price  total_sqft_int  bhk  price_per_sqft   
0   3.0      2.0  150.0          1672.0    3     8971.291866  \
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area   
0                              1                        0  \
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  ...   
0                    0                           1  ...  \
1                    0                           1  ...   
2                    0                           1  ...   
3                    0                           1  ...   
4                    1                           1  ...   

   location_Kalena Agrahara  location_Horamavu Agara  location_Vidyaranyapura   
0                         0                        0                        0  \
1                         0                        0                        0   
2                         0                        0                        0   
3                         0                        0                        0   
4                         0                        0                        0   

   location_BTM 2nd Stage  location_Hebbal Kempapura  location_Hosur Road   
0                       0                          0                    0  \
1                       0                          0                    0   
2                       0                          0                    0   
3                       0                          0                    0   
4                       0                          0                    0   

   location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura   
0                            0                0                     0  \
1                            0                0                     0   
2                            0                0                     0   
3                            0                0                     0   
4                            0                0                     0   

   location_Tumkur Road  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  

[5 rows x 108 columns]

Split the data


In [5]:
x = df.drop("price", axis = 1)
y = df["price"]

In [6]:
print(x)

      bath  balcony  total_sqft_int  bhk  price_per_sqft   
0      3.0      2.0          1672.0    3     8971.291866  \
1      3.0      3.0          1750.0    3     8514.285714   
2      3.0      2.0          1750.0    3     8571.428571   
3      2.0      2.0          1250.0    2     3200.000000   
4      2.0      2.0          1200.0    2     6916.666667   
...    ...      ...             ...  ...             ...   
7115   3.0      2.0          2900.0    3    11206.896552   
7116   3.0      1.0          1780.0    3     4765.730337   
7117   2.0      1.0           880.0    2     5454.545455   
7118   2.0      1.0          1000.0    2     5500.000000   
7119   2.0      1.0          1400.0    3     5571.428571   

      area_typeSuper built-up  Area  area_typeBuilt-up  Area   
0                                 1                        0  \
1                                 0                        1   
2                                 1                        0   
3                      

In [7]:
print(y)

0       150.00
1       149.00
2       150.00
3        40.00
4        83.00
         ...  
7115    325.00
7116     84.83
7117     48.00
7118     55.00
7119     78.00
Name: price, Length: 7120, dtype: float64


In [8]:
print("Shape of X : ", x.shape)
print("Shape of Y :", y.shape)

Shape of X :  (7120, 107)
Shape of Y : (7120,)


In [9]:
from sklearn.model_selection import train_test_split


In [37]:
x_train , x_test , y_train , y_test = train_test_split(x, y , test_size = 0.2, random_state = 0)

In [38]:
print("Shape of x_train : ", x_train.shape)
print("Shape of y_train : ", y_train.shape)
print("shape of x_test : ", x_test.shape)
print("Shape of y_test : ", y_test.shape)

Shape of x_train :  (5696, 107)
Shape of y_train :  (5696,)
shape of x_test :  (1424, 107)
Shape of y_test :  (1424,)


Feature Scaling

In [39]:
from sklearn.preprocessing import StandardScaler

In [40]:
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

Linear Regression - ML Model Training

In [41]:
from sklearn.linear_model import LinearRegression

In [42]:
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [43]:
model.coef_

array([ 2.72733097e-02, -5.66780386e-01,  7.85493387e+01, -1.28223806e+01,
        6.62347113e+01, -1.88307325e+00, -3.74242299e+00, -5.43206396e+00,
       -1.84642396e+00, -3.60058667e+00, -2.49842892e+00,  4.00166352e-01,
       -1.16360370e+00,  2.24410163e+00,  1.87586670e-01, -1.41125022e+00,
       -4.44912836e-01,  2.57389864e+00, -1.75777014e+00,  2.66716762e+00,
       -3.14023786e+00, -1.78789199e+00, -1.02777303e+00, -2.87521308e-02,
        1.40791031e+00,  1.82176921e+00, -5.59068059e+00, -9.28301424e-01,
       -6.03366685e-01,  1.88159434e+00, -5.29576978e-01, -4.98745475e-01,
        7.12787558e-01, -1.48295499e+00,  1.12044791e-01, -1.58769898e+00,
        5.13148322e-01,  7.26498264e-01,  3.96764027e+00,  2.49730952e-01,
        4.05281231e-01,  3.05752126e-01, -3.35033606e-01,  1.21381533e+00,
       -1.65039967e+00, -2.78769102e+00, -7.97284009e-03,  4.90588404e-02,
       -7.49095121e-01, -2.39751003e+00, -1.13951982e+00,  5.52757261e-01,
        1.15376796e+00, -

In [44]:
model.intercept_

96.69880969101122

Predict the value of Home and Test

In [45]:
x_test[0,:]

array([-0.44764781,  0.55247268, -0.0552982 , -0.55282023, -0.45981003,
        0.57032234, -0.46788587, -0.25509029,  0.51635472, -0.18474894,
       -0.16332875, -0.14979193, -0.12741862, -0.13231119, -0.12670528,
       -0.1208567 , -0.12812824, -0.12381344, -0.12308052, -0.11551113,
       -0.11472827, -0.1107353 , -0.10743948, -0.11234866, -0.09121434,
       -0.09218776, -0.08923672, -0.08085949, -0.08618799, -0.08721571,
       -0.08618799, -0.08514823, -0.08409599, -0.07276497, -0.08514823,
       -0.08085949, -0.0739743 , -0.07153563, -0.08085949, -0.07633675,
       -0.0677166 , -0.07633675, -0.07633675, -0.0739743 , -0.0739743 ,
       -0.06901264, -0.0751646 , -0.07153563, -0.07633675, -0.07749158,
       -0.06901264, -0.0677166 , -0.07028523, -0.0677166 , -0.06901264,
       -0.06367332, -0.06639573, -0.06367332, -0.0677166 , -0.06367332,
       -0.05935999, -0.05935999, -0.05785186, -0.06367332, -0.06226825,
       -0.06639573, -0.05935999, -0.06226825, -0.06083125, -0.05

In [46]:
model.predict([ x_test[0,:] ])

array([71.59875011])

In [47]:
model.predict(x_test)

array([ 71.59875011,   4.51459147,  41.66671239, ...,  60.55337082,
        91.34226955, 731.42804949])

In [48]:
y_test

1189     68.0
5876     36.0
5597     61.0
3391     85.0
6122     64.0
        ...  
5830    187.0
4887     57.0
1861     90.0
3014     75.0
1670    864.0
Name: price, Length: 1424, dtype: float64

In [49]:
# score
model.score(x_test, y_test)

0.8979105726539878

Implementing Ridge and Lasso Regression

In [50]:
from sklearn.linear_model import Ridge, Lasso

In [51]:
rd = Ridge()


In [52]:
rd.fit(x_train, y_train)

Ridge()

In [65]:
rd.score(x_test, y_test)

0.8979774363643058

In [54]:
lss = Lasso()

In [55]:
lss.fit(x_train, y_train)

Lasso()

In [66]:
lss.score(x_test, y_test)

0.9030087395008762

Ridge & Lasso with parameter : alpha 

In [61]:
rd2 = Ridge(alpha = 2)
rd2.fit(x_train, y_train)

Ridge(alpha=2)

In [67]:
rd2.score(x_test, y_test)

0.8980439780735657

In [63]:
lss2 = Lasso(alpha = 2)
lss2.fit(x_train ,y_train)

Lasso(alpha=2)

In [68]:
lss2.score(x_test, y_test)

0.9034577094296147

Thanks For visiting